/**
 * Radio stations from TAVR Media
 */
export enum RadioStation {
  HitFM = "hit",
  HitFMUkraine = "hitu",
  HitFMBest = "hitb",
  HitFMTop = "hitt",
  Bayraktar = "radio3bayraktar",
  Roks = "roks",
  RoksUkraine = "roksukr",
  RoksNew = "roksnew",
  RoksClassic = "rokscla",
  RoksHardnHeavy = "rokshar",
  RoksBallads = "roksbal",
  KissFM = "kiss",
  KissFMUkraine = "kissukr",
  KissFMDeep = "kissdeep",
  KissFMDigital = "kissdigital",
  Relax = "relax",
  RelaxUkraine = "relaxukr",
  RelaxInternational = "relaxint",
  RelaxCafe = "relaxcafe",
  RelaxInstrumental = "relaxinstrumental",
  MelodiaFM = "melodia",
  MelodiaFMInternational = "melodiaint",
  MelodiaFMDisco = "melodiad",
  MelodiaFMRomantic = "melodiar",
  NasheRadio = "nasheradio",
  NasheRadioUkraine = "nasheradio3ukr",
  RadioJazz = "jazz",
  RadioJazzUkraine = "jazz3ukr",
  RadioJazzGold = "jazz3gold",
  RadioJazzLight = "jazz3light",
  RadioJazzCover = "jazz3cover",
  RadioJazzGroove = "jazz3groove",
  ClassicRadio = "radio3classic",
  GuliayRadio = "radio3guliay",
  RadioGold = "radio3gold",
  FlashRadio = "radio3flash",
  IndieUARadio = "radio3indieua",
  UnitedNews = "news",
}

/**
 * Default radio stations URLs
 */
export enum RadioPlayerURL {
  HitFM = "https://online.hitfm.ua/HitFM",
  HitFMUkraine = "https://online.hitfm.ua/HitFM_Ukr",
  HitFMBest = "https://online.hitfm.ua/HitFM_Best",
  HitFMTop = "https://online.hitfm.ua/HitFM_Top",
  Bayraktar = "https://online.radiobayraktar.ua/RadioBayraktar",
  Roks = "https://online.radioroks.ua/RadioROKS",
  RoksUkraine = "https://online.radioroks.ua/RadioROKS_Ukr",
  RoksNew = "https://online.radioroks.ua/RadioROKS_NewRock",
  RoksClassic = "https://online.radioroks.ua/RadioROKS_ClassicRock",
  RoksHardnHeavy = "https://online.radioroks.ua/RadioROKS_HardnHeavy",
  RoksBallads = "https://online.radioroks.ua/RadioROKS_Ballads",
  KissFM = "https://online.kissfm.ua/KissFM",
  KissFMUkraine = "https://online.kissfm.ua/KissFM_Ukr",
  KissFMDeep = "https://online.kissfm.ua/KissFM_Deep",
  KissFMDigital = "https://online.kissfm.ua/KissFM_Digital",
  Relax = "https://online.radiorelax.ua/RadioRelax",
  RelaxUkraine = "https://online.radiorelax.ua/RadioRelax_Ukr",
  RelaxInternational = "https://online.radiorelax.ua/RadioRelax_Int",
  RelaxCafe = "https://online.radiorelax.ua/RadioRelax_Cafe",
  RelaxInstrumental = "https://online.radiorelax.ua/RadioRelax_Instrumental",
  MelodiaFM = "https://online.melodiafm.ua/MelodiaFM",
  MelodiaFMInternational = "https://online.melodiafm.ua/MelodiaFM_Int",
  MelodiaFMDisco = "https://online.melodiafm.ua/MelodiaFM_Disco",
  MelodiaFMRomantic = "https://online.melodiafm.ua/MelodiaFM_Romantic",
  NasheRadio = "https://online.nasheradio.ua/NasheRadio",
  NasheRadioUkraine = "https://online.nasheradio.ua/NasheRadio_Ukr",
  RadioJazz = "https://online.radiojazz.ua/RadioJazz",
  RadioJazzUkraine = "https://online.radiojazz.ua/RadioJazz_Ukr",
  RadioJazzGold = "https://online.radiojazz.ua/RadioJazz_Gold",
  RadioJazzLight = "https://online.radiojazz.ua/RadioJazz_Light",
  RadioJazzCover = "https://online.radiojazz.ua/RadioJazz_Cover",
  RadioJazzGroove = "https://online.radiojazz.ua/RadioJazz_Groove",
  ClassicRadio = "https://online.classicradio.com.ua/ClassicRadio",
  GuliayRadio = "https://online.radioplayer.ua/GuliayRadio",
  RadioGold = "https://online.radioplayer.ua/RadioGold",
  FlashRadio = "https://online.radioplayer.ua/FlashRadio",
  IndieUARadio = "https://online.radioplayer.ua/RadioIndieUA",
  UnitedNews = "https://online-news.radioplayer.ua/RadioNews",
}
